stages:
  - pre_check
  - build
  - deploy

variables:
  GIT_STRATEGY: clone
  GET_SOURCES_ATTEMPTS: "10"
  ARTIFACT_DOWNLOAD_ATTEMPTS: "10"
  GIT_SUBMODULE_STRATEGY: none
  IDF_SKIP_CHECK_SUBMODULES: 1
  GIT_DEPTH: 1

before_script:
  - source ${CI_PROJECT_DIR}/tools/ci/utils.sh
  - add_gitlab_ssh_keys

include:
  - '.gitlab/ci/rules.yml'
  - '.gitlab/ci/common.yml'
#  - '.gitlab/ci/pre_check.yml'
#  - '.gitlab/ci/build_webrtc_solutions.yml'
  - '.gitlab/ci/deploy.yml'
